version: "3.9"
services:
  jwcfrontend:
    image: quay.io/kurama/jwc-frontend:prod
    restart: always
    labels:
      - traefik.frontend.rule=Host:jwc-frontend.mamun.cloud
    networks:
     - internal
     - web
    ports:
      - "80:8080"
networks:
 web:
   external: true
 internal:
   external: false