version: "3.9"
services:
  jwcfrontend:
    image: quay.io/kurama/jwc-frontend
    restart: always
    labels:
      - traefik.frontend.rule=Host:jwc-front.mamun.cloud
    networks:
     - internal
     - web
    ports:
      - "8003:8003"
networks:
 web:
   external: true
 internal:
   external: false

