version: "3.9"
services:
  jwcfrontend:
    image: quay.io/kurama/jwc-frontend:main
    restart: always
    labels:
      - traefik.http.routers.admin.rule=Host(`jwcindia.com`)
      - traefik.http.routers.admin.tls=true
      - traefik.http.routers.admin.tls.certresolver=lets-encrypt
      - traefik.port=8003
    networks:
     - internal
     - web
    ports:
      - "8003:8003"
networks:
 web:
   external: true
 internal:
   external: false