version: "3.9"
services:
  jwcfrontend:
    image: quay.io/kurama/jwc-frontend:main
    restart: always
    labels:
      - traefik.frontend.rule=Host:jwcindia.com,www.jwcindia.com
    networks:
     - internal
     - web
    ports:
      - "8003:8003"
networks:
 web:
   external: true
 internal:
   external: false