version: "3.9"
services:
  jwcfrontend:
    image: quay.io/kurama/jwc-frontend:main
    restart: always
    labels:
      - traefik.http.routers.front.rule=Host(`jwcindia.com`)
      - traefik.http.routers.front.tls=true
      - traefik.http.routers.front.tls.certresolver=lets-encrypt
      - traefik.port=8003
    networks:
     - web
    ports:
      - "8003:8003"
networks:
 web:
   external: true