
import Head from 'next/head';
import Product from '@/components/singleproduct';
import SubLayout from '@/Layouts/sub';
export default function Home() {
  return (
    <>
      <Head>
        <title>JWC India - Product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Product />
       
      </main>
    </>
  )
}

Home.getLayout = function (page: any) {
  return <SubLayout>{page}</SubLayout>;
};
