
import Head from 'next/head';
import Product from '@/components/singleproduct';
import Layout from '@/Layouts/default';
import { fetchHomeData, fetchItemsData, fetchTables } from '@/requests/requests';
import { useAppContext } from '@/store/store';
import { trimChild, setDataChild, setDataParents, addChildToParent } from '@/store/utils';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function SProduct({homedata, items, tables}: any) {


  const { state, setState } = useAppContext();

  useEffect(() => {
             setState({ ...state, 
                homedata:  homedata,
                items: items,
                itemsHome: trimChild(items),
                childItems: setDataChild(items), 
                childHome: trimChild(setDataChild(items)),
                mainHome: trimChild(setDataParents(items)),
                mainItems: setDataParents(items), 
                Tables: tables,
             });
  }, []);
  
  return (
    <>
      <Head>
        <title>JWC India - Product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Product data={items} tables={tables} />
       
      </main>
    </>
  )
}

export const getServerSideProps = async (context: any) => {
  const homedata = await fetchHomeData()
  const tables = await fetchTables()
  const items = await fetchItemsData()
  const navitems = addChildToParent(items)
  return {
      props: {homedata, items, tables, navitems},
  };
  
}

SProduct.getLayout = function (page: any) {
  return <Layout>{page}</Layout>;
};
