import Layout from '@/Layouts/default';
import Head from 'next/head';
import ShopByCategoryGrid from '@/components/shopByCategoriesGrid';
import ProdsCarousel from '@/components/prodsCarousel';
import ProdsGrid from './prodsGrid';
export default function Home() {
  return (
    <>
      <Head>
        <title>JWC India</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
          <ShopByCategoryGrid/>
        </div>

        <div className="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
         <ProdsGrid/>
        </div>
       
      </main>
    </>
  )
}

Home.getLayout = function (page: any) {
  return <Layout>{page}</Layout>;
};
