import Layout from '@/Layouts/default';
import Head from 'next/head';
import Hero from '@/components/hero';
import MainProducts, { MixedProducts } from '@/components/mainproducts';
import Products from '@/components/products';
import Services from '@/components/services';
import Contact from '@/components/contact';
import { fetchHomeData, fetchItemsData, fetchTables } from '@/requests/requests';
import About from '@/components/about';
import { useAppContext } from '@/store/store';
import { useEffect } from 'react';
import { trimChild, setDataChild, setDataParents, addChildToParent } from '@/store/utils';

export default function Home({homedata, items, tables, navitems}: any) {

  const { state, setState } = useAppContext();

  useEffect(() => {
             console.log(items)
             setState({ ...state, 
                homedata:  homedata,
                items: items,
                itemsHome: trimChild(items),
                childItems: setDataChild(items), 
                childHome: trimChild(setDataChild(items)),
                mainHome: trimChild(setDataParents(items)),
                mainItems: setDataParents(items), 
                Tables: tables,
             });
  }, []);
  
  return (
    <>
      <Head>
        <title>JWC India</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        
         <Hero data={homedata} />

          <About />

          {/* <HeroSection/>  */}

          <MixedProducts trim={true}/>
       

        {/* <div className="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
          <ShopByCategoryGrid/>
        </div> 

        <Products trim={true} />*/}

        {/* <div className="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
         <ProdsGrid/>
        </div> */}
         
         <div id='about'><Services /></div>

         <div id='contact'><Contact /></div>

       {/*  <div className="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
         <OurServices/>
        </div> */}
       
      </main>
    </>
  )
}

export const getServerSideProps = async (context: any) => {
  const homedata = await fetchHomeData()
  const tables = await fetchTables()
  
  const items = await fetchItemsData()
  const navitems = addChildToParent(items)
  return {
      props: {homedata, items, tables, navitems},
  };
  
}

Home.getLayout = function (page: any) {
  return <Layout>{page}</Layout>;
};
