
import Head from 'next/head';
import Products from '@/components/products';

import SubLayout from '@/Layouts/sub';
export default function Home() {
    return (
        <>
            <Head>
                <title>JWC India - Products</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <Products trim={false} />

                

            </main>
        </>
    )
}

Home.getLayout = function (page: any) {
    return <SubLayout>{page}</SubLayout>;
};
