
import Head from 'next/head';
import Products from '@/components/products';

import Layout from '@/Layouts/default';
import { fetchHomeData, fetchItemsData, fetchTables } from '@/requests/requests';
import { useAppContext } from '@/store/store';
import { trimChild, setDataChild, setDataParents, addChildToParent } from '@/store/utils';
import { useEffect } from 'react';
export default function MProducts({homedata, items, tables}: any) {
    const { state, setState } = useAppContext();

  useEffect(() => {
             setState({ ...state, 
                homedata:  homedata,
                items: items,
                itemsHome: trimChild(items),
                childItems: setDataChild(items), 
                childHome: trimChild(setDataChild(items)),
                mainHome: trimChild(setDataParents(items)),
                mainItems: setDataParents(items), 
                Tables: tables,
             });
  }, []);
    return (
        <>
            <Head>
                <title>JWC India - Products</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <Products trim={false} />

            </main>
        </>
    )
}

export const getServerSideProps = async (context: any) => {
    const homedata = await fetchHomeData()
    const tables = await fetchTables()
    
    const items = await fetchItemsData()
    const navitems = addChildToParent(items)
    return {
        props: {homedata, items, tables, navitems},
    };
    
  }

MProducts.getLayout = function (page: any) {
    return <Layout>{page}</Layout>;
};
